# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xa7a100tfgg484-2I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.cache/wt [current_project]
set_property parent.project_path /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.srcs/sources_1/new/Flash_SPI.vhd
  /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.srcs/sources_1/new/Head.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.srcs/constrs_1/new/top_level.xdc
set_property used_in_implementation false [get_files /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet_Artix/Carcasa.srcs/constrs_1/new/top_level.xdc]


synth_design -top En_Head -part xa7a100tfgg484-2I


write_checkpoint -force -noxdef En_Head.dcp

catch { report_utilization -file En_Head_utilization_synth.rpt -pb En_Head_utilization_synth.pb }
