# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz.xci
# IP: The module: 'Phasing_CLK_125MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Phasing_CLK_125MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Phasing_CLK_125MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Phasing_CLK_125MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz.xci
# IP: The module: 'Phasing_CLK_125MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Phasing_CLK_125MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Phasing_CLK_125MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/farbizu/GIT/Jaquenod/Trabajo_Final/Ethernet-comunication-VHDL/Ethernet-comunication-VHDL.srcs/sources_1/ip/Phasing_CLK_125MHz/Phasing_CLK_125MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Phasing_CLK_125MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
