# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.cache/wt [current_project]
set_property parent.project_path /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/imports/Trabajo_Final/Cod_8b10b/Cod_8b10b.ip_user_files/mem_init_files/DCh.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/imports/Trabajo_Final/Cod_8b10b/Cod_8b10b.ip_user_files/mem_init_files/Dplus.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/imports/Trabajo_Final/Cod_8b10b/Cod_8b10b.ip_user_files/mem_init_files/KCh.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/imports/Trabajo_Final/Cod_8b10b/Cod_8b10b.ip_user_files/mem_init_files/Kplus.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/Dec_8b10b/Dec_8b10b.ip_user_files/mem_init_files/Inv_Ch.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/Dec_8b10b/Dec_8b10b.ip_user_files/mem_init_files/Inv_Dplus.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/Dec_8b10b/Dec_8b10b.ip_user_files/mem_init_files/Inv_Kplus.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/Cod_8b10b/Cod_8b10b.ip_user_files/mem_init_files/KCh.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/Cod_8b10b/Cod_8b10b.ip_user_files/mem_init_files/Kplus.coe
add_files /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.ip_user_files/mem_init_files/Inv_Ch.coe
read_vhdl -library xil_defaultlib {
  /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/imports/Trabajo_Final/Cod_8b10b/Cod_8b10b.srcs/sources_1/new/Cod_8b10b.vhd
  /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/imports/Trabajo_Final/Dec_8b10b/Dec_8b10b.srcs/sources_1/new/Dec_8b10b.vhd
  /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/new/Head.vhd
}
read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/DCh/DCh.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/DCh/DCh_ooc.xdc]

read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Dplus/Dplus.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Dplus/Dplus_ooc.xdc]

read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/KCh/KCh.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/KCh/KCh_ooc.xdc]

read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Kplus/Kplus.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Kplus/Kplus_ooc.xdc]

read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Inv_Ch/Inv_Ch.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Inv_Ch/Inv_Ch_ooc.xdc]

read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Inv_Dplus/Inv_Dplus.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Inv_Dplus/Inv_Dplus_ooc.xdc]

read_ip -quiet /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Inv_Kplus/Inv_Kplus.xci
set_property used_in_implementation false [get_files -all /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Inv_Kplus/Inv_Kplus_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top En_Head -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef En_Head.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file En_Head_utilization_synth.rpt -pb En_Head_utilization_synth.pb"
