# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fede/GIT/Jaquenod/Modulo11/Guia/ISE/Actividad_11_2_1/Cod_8b10b/Cod_8b10b.srcs/sources_1/ip/KCh/KCh.xci
# IP: The module: 'KCh' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fede/GIT/Jaquenod/Modulo11/Guia/ISE/Actividad_11_2_1/Cod_8b10b/Cod_8b10b.srcs/sources_1/ip/KCh/KCh_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'KCh'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/fede/GIT/Jaquenod/Modulo11/Guia/ISE/Actividad_11_2_1/Cod_8b10b/Cod_8b10b.srcs/sources_1/ip/KCh/KCh.xci
# IP: The module: 'KCh' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fede/GIT/Jaquenod/Modulo11/Guia/ISE/Actividad_11_2_1/Cod_8b10b/Cod_8b10b.srcs/sources_1/ip/KCh/KCh_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'KCh'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
