# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Kplus/Kplus.xci
# IP: The module: 'Kplus' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Kplus/Kplus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Kplus'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Kplus/Kplus.xci
# IP: The module: 'Kplus' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fede/GIT/Jaquenod/Trabajo_Final/System_8b10b/System_8b10b.srcs/sources_1/ip/Kplus/Kplus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Kplus'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
